### ISSUE TITLE
No such file or directory: 'data/CAMERA/val_list.txt'.

### ISSUE THREAD

**Issue by lh641446825** [mentian/object-deformnet#3]
Sorry for bothering you. When I run  the file `evaluate.py`, the following problems occurred:

> `FileNotFoundError: [Errno 2] No such file or directory: 'data/CAMERA/val_list.txt'.

I did not find this file in the dataset，can you provide “val_list.txt” and “train_list.txt”？

When I run  the file `train_ae.py`，the “data/obj_models/ShapeNetCore_4096.h5” file  is not in the dataset, either.

**Comment by mentian** [comment]
You need to run the scripts (shape_data.py and pose_data.py) first to prepare all these files.

**Comment by mentian** [comment]
I copied this model form the ShapeNetCore. The original model should be fine.

**Comment by Liuchongpei** [comment]
@trevor-taeyeop Hi, same problem, have you fixed it?

**Comment by mentian** [comment]
Try the original model in ShapeNetCore, Let me know if you couldn't fix this problem, I will upload this specific model for you to download.

**Comment by taeyeopl** [comment]
Can I ask about the original ShapeNetCore?? 
Does it represent v1 or v2 or other things?? 
It would be very helpful if you share files.

**Comment by taeyeopl** [comment]
@Liuchongpei, Have you tried the evaluation using pretrained weights and compared it with the paper results?? https://github.com/mentian/object-deformnet/issues/6#issue-703334926

**Comment by mentian** [comment]
I copied the model from ShapeNetCoreV1. You might download this specific model form [here](https://drive.google.com/file/d/1rWkxEVJJh_kWIqxudn_i6sJ-hhd0E7TV/view?usp=sharing).

**Comment by dschaehi** [comment]
> I copied the model from ShapeNetCoreV1. You might download this specific model form [here](https://drive.google.com/file/d/1rWkxEVJJh_kWIqxudn_i6sJ-hhd0E7TV/view?usp=sharing).

Could you put this patch to README.md as this is a known problem?
