### ISSUE TITLE
Error When Running shape_data.py

### ISSUE THREAD

**Issue by LiSh1Ln** [mentian/object-deformnet#33]
When I run  shape_date.py，I meet this error：
File "/home/lsl/GenPose/GenPose/preprocess/../lib/utils.py", line 104, in uniform_sample
    faces = vertices[faces]
IndexError: arrays used as indices must be of integer (or boolean) type
My environment is ：
Ubuntu 20.04
Python 3.8.15
Pytorch 1.12.0
Pytorch3d 0.7.2
CUDA 11.3

So I want to know ,Do I need to be consistent with your environment?

**Comment by c1onaldo** [comment]
i also met the question，how do you solve it

**Comment by LeGJin** [comment]
@c1onaldo i also met the question，how do you solve it？

**Comment by LeGJin** [comment]
@LiSh1Ln hello ，how do you solve it？

**Comment by yong0913** [comment]
@jinguangle hello ，how do you solve it？

**Comment by LeGJin** [comment]
@yong0913 no,i haven't sloved it,do you slove it?
