### ISSUE TITLE
Question about ground-truth NOCS

### ISSUE THREAD

**Issue by taeyeopl** [mentian/object-deformnet#4]
Thanks for sharing good work. 
I have very simple question about ground-truth NOCS. 

As I understand, NOCS is normalization coordinate and it doesn't need 6D Pose information(R,T). 
In the paper, to make ground-truth NOCS coordinate, object model and its 6D pose through image rendering was used. 
Could you explain why the 6D pose and image rendering was used??

**Comment by mentian** [comment]
Not sure if I get your question.
In our paper, NOCS coordinates refers to the points (corresponding to observed pixels) in the Normalized Object Coordinate Space. The general method to obtain this ground truth is to render the object to an image with ground truth 6D pose. This rendering at ground truth pose is meant to establish these correspondences.
Fortunately, this rendering step has been done by the original work of NOCS. The results are provided as _coord.png in their datasets.

**Comment by taeyeopl** [comment]
Thanks !!
