### ISSUE TITLE
Question about evaluation performance

### ISSUE THREAD

**Issue by taeyeopl** [mentian/object-deformnet#6]
I downloaded and used your pretrained model, but I couldn't get the reported result. 
Q1. Can I ask which part am I missed?? 

```
Total images: 2754
Valid images: 2754,  Total instances: 15573,  Average: 5.65/image
Inference time: 86.035171  Average: 0.031240/image
Umeyama time: 104.452625  Average: 0.037928/image
Total time: 323.474025
mAP:
3D IoU at 25: 81.9
3D IoU at 50: 71.0
3D IoU at 75: 43.1
5 degree, 2cm: 11.4
5 degree, 5cm: 12.0
10 degree, 2cm: 33.5
10 degree, 5cm: 37.8
Acc:
3D IoU at 25: 90.3
3D IoU at 50: 82.9
3D IoU at 75: 57.5
5 degree, 2cm: 23.3
5 degree, 5cm: 24.5
10 degree, 2cm: 45.5
10 degree, 5cm: 50.2

```
![mAP](https://user-images.githubusercontent.com/50736858/93433092-56840e80-f901-11ea-9439-b82c089ddc79.png)

**Comment by mentian** [comment]
I have run the evaluation several times. With the released model, similar results should be expected. 
Did you follow the instructions in README when you prepare the dataset?

**Comment by taeyeopl** [comment]
Yeah, I followed your instructions. 
(shape_data.py) There are some issues in this part. https://github.com/mentian/object-deformnet/issues/3#issuecomment-672858239
and (pose_data.py) I found some real_test background value was 0 , instead of 255 value. So I change 0 value to 255. 

My graph is visually close to your graph (FIg4, in the paper).

**Comment by mentian** [comment]
kind of busy, will respond to you in the next couple days.

**Comment by AmethystZeroAtwell** [comment]
I used pretrained model to evaluate real-test dataset and got results similar to yours.
```
mAP:
3D IoU at 25: 79.3
3D IoU at 50: 68.4
3D IoU at 75: 40.4
5 degree, 2cm: 11.5
5 degree, 5cm: 12.1
10 degree, 2cm: 33.5
10 degree, 5cm: 37.8
Acc:
3D IoU at 25: 89.8
3D IoU at 50: 82.4
3D IoU at 75: 56.8
5 degree, 2cm: 23.4
5 degree, 5cm: 24.5
10 degree, 2cm: 45.5
10 degree, 5cm: 50.1
```

**Comment by mentian** [comment]
Could you confirm that you specify the correct mode path in evaluate.py? To evaluate on the real_test dataset, you need to set the value for both --data and --model.
I actually run evaluation on real test dataset with the pre-trained model for CAMERA, and get similar result as you provided. I guess this might be the reason.
Please let me know if this does not solve your problem.

**Comment by taeyeopl** [comment]
Thanks, the problem was solved !!

```
Total images: 2754
Valid images: 2754,  Total instances: 15573,  Average: 5.65/image
Inference time: 113.280357  Average: 0.041133/image
Umeyama time: 177.431597  Average: 0.064427/image
Total time: 462.305699
Evaluating ...
mAP:
3D IoU at 25: 83.4
3D IoU at 50: 77.4
3D IoU at 75: 53.5
5 degree, 2cm: 19.5
5 degree, 5cm: 21.6
10 degree, 2cm: 43.5
10 degree, 5cm: 54.0
Acc:
3D IoU at 25: 91.5
3D IoU at 50: 87.7
3D IoU at 75: 69.4
5 degree, 2cm: 31.6
5 degree, 5cm: 34.3
10 degree, 2cm: 55.0
10 degree, 5cm: 63.1
```

**Comment by pppkkk611** [comment]
> 谢谢，问题解决了！！
> 
> ```
> Total images: 2754
> Valid images: 2754,  Total instances: 15573,  Average: 5.65/image
> Inference time: 113.280357  Average: 0.041133/image
> Umeyama time: 177.431597  Average: 0.064427/image
> Total time: 462.305699
> Evaluating ...
> mAP:
> 3D IoU at 25: 83.4
> 3D IoU at 50: 77.4
> 3D IoU at 75: 53.5
> 5 degree, 2cm: 19.5
> 5 degree, 5cm: 21.6
> 10 degree, 2cm: 43.5
> 10 degree, 5cm: 54.0
> Acc:
> 3D IoU at 25: 91.5
> 3D IoU at 50: 87.7
> 3D IoU at 75: 69.4
> 5 degree, 2cm: 31.6
> 5 degree, 5cm: 34.3
> 10 degree, 2cm: 55.0
> 10 degree, 5cm: 63.1
> ```

Hello, I have set the data to real_ test and model are also set to real/model_50.pth, but the result is still consistent with your first attempt. May I ask how you resolved it at that time？

**Comment by pppkkk611** [comment]
> Thanks, the problem was solved !!
> 
> ```
> Total images: 2754
> Valid images: 2754,  Total instances: 15573,  Average: 5.65/image
> Inference time: 113.280357  Average: 0.041133/image
> Umeyama time: 177.431597  Average: 0.064427/image
> Total time: 462.305699
> Evaluating ...
> mAP:
> 3D IoU at 25: 83.4
> 3D IoU at 50: 77.4
> 3D IoU at 75: 53.5
> 5 degree, 2cm: 19.5
> 5 degree, 5cm: 21.6
> 10 degree, 2cm: 43.5
> 10 degree, 5cm: 54.0
> Acc:
> 3D IoU at 25: 91.5
> 3D IoU at 50: 87.7
> 3D IoU at 75: 69.4
> 5 degree, 2cm: 31.6
> 5 degree, 5cm: 34.3
> 10 degree, 2cm: 55.0
> 10 degree, 5cm: 63.1
> ```

Hello, I have set the data to real_ test and model are also set to real/model_50.pth, but the result is still consistent with your first attempt. May I ask how you resolved it at that time？
