### ISSUE TITLE
Confusion about Evaluation Metric

### ISSUE THREAD

**Issue by Liuchongpei** [mentian/object-deformnet#7]
Hello, thanks for your great work. I don't have a thorough understanding of the evaluation metric, and I hope to get your help. I only found the definition of mAP for 2D object detection. Is the calculation of mAP about 3D IoU and _n_ ° _m_ cm the same as the calculation steps of 2D object detection mAP, except that the threshold for judging FP and TP is changed from IoU to 3D IoU and _n_ ° _m_ cm? In addition, what does **Acc** mean?

**Comment by mentian** [comment]
Yes, it's same as 2D object detection.
Acc means accuracy.

**Comment by Liuchongpei** [comment]
Thanks for reply. It seems that there is no TN in object detection, so there is no "accuracy". Do you mean "**precision**"?

**Comment by mentian** [comment]
Yes, you are right.
We actually compute the "accuracy" as "number of correct predictions / number of all predictions" . https://github.com/mentian/object-deformnet/blob/a2dcdb87dd88912c6b51b0f693443212fde5696e/lib/utils.py#L504
For consistent comparison with previous works, mAP is preferred.

**Comment by Liuchongpei** [comment]
Okay, thanks!
