### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by DC1991** [mentian/object-deformnet#9]
Dear author, in your paper, you mentioned that you treated the mug as a symmetric object when the handle is unseen. But how to get handle the visibility of mug in real-test dataset? Thanks very much.

**Comment by mentian** [comment]
The visibility of handle is provided by the original dataset. You may refer to [NOCS](https://github.com/hughw19/NOCS_CVPR2019).

**Comment by DC1991** [comment]
Hi @mentian , thanks for your reply. I can only find visibility information in val dataset. The origin test dataset only provides pose information and image path. Do I miss something?

**Comment by mentian** [comment]
Some of the data in original test dataset might miss the visibility information. Please refer to this [line](https://github.com/hughw19/NOCS_CVPR2019/blob/a7780dd9ab100f185f4b30093306325200f3192e/detect_eval.py#L206) and the following code block for how NOCS handles the visibility information.

In our implementation, we directly copy the visibility information from the detection results of NOCS ([here](https://github.com/mentian/object-deformnet/blob/a2dcdb87dd88912c6b51b0f693443212fde5696e/preprocess/pose_data.py#L310)).
If you prefer a quick solution, please download the zip file provided in "Section Evaluation of README". This file contains the detection results of NOCS, which contain the handle visibility for each image of both real test and val dataset.

**Comment by DC1991** [comment]
I see, I will figure out how to do it. Thanks for your detailed answer.
